name: flask_ML_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - flask=2.0.2
  - flask-sqlalchemy=2.5.1
  - flask-wtf=1.0.0
  - flask-login=0.5.0
  - sqlalchemy=1.4.30
  - numpy=1.22.1
  - pandas=1.4.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - pillow=9.0.0
  - cffi=1.15.0
  - pytorch=1.10.1
  - torchvision=0.11.2
  - cpuonly  # Only if you don't need GPU support
  - pip
  - pip:
      - bcrypt==3.2.0
      - certifi==2021.10.8
      - charset-normalizer==2.0.10
      - click==8.0.1
      - colorama==0.4.4
      - greenlet==1.1.2
      - idna==3.3
      - itsdangerous==2.0.1
      - Jinja2==3.0.2
      - joblib==1.1.0
      - MarkupSafe==2.0.1
      - python-dateutil==2.8.2
      - pytz==2021.3
      - requests==2.27.1
      - six==1.16.0
      - threadpoolctl==3.0.0
      - typing_extensions==4.0.1
      - urllib3==1.26.8
      - Werkzeug==2.0.2
      - WTForms==3.0.1
      - gunicorn==20.0.4
